### ISSUE TITLE
Karate IntelliJ plugin state unexpected end of file when using example table variables without quotes

### ISSUE THREAD

**Issue by PBMax02** [karatelabs/karate-intellij-plugin#29] opened 2023-04-28 13:59 UTC
Using the Karate plugin 1.7.4.325 I see that previously valid test are now showing errors in the IDE.
This relates to using the example table variables in my test without enclosing them in quotes.

This looks like it may only affect the Given URL step as the headers step doesn't complain.

![image](https://user-images.githubusercontent.com/68280714/235167954-a81db336-17e8-40cc-a494-ab9314472379.png)

**Comment by ptrthomas** [comment] 2023-05-01 11:34
duplicate of #24

**Closed by ptrthomas** 2023-05-01 11:34 UTC
Labels: duplicate
