### ISSUE TITLE
karate.filterKeys() is sometimes preventing the next Scenario from being executable from the gutter

### ISSUE THREAD

**Issue by staffier** [karatelabs/karate-intellij-plugin#12] opened 2022-07-19 20:22 UTC
Here is an example, where the 2nd scenario will have no gutter icon offered as a result of `karate.filterKeys()` (it will still run when you execute the whole feature): 

```gherkin
Feature:

  Scenario: filterKeys
    * def test = { a: '1', b: '2' }
    * match karate.filterKeys(test, 'b') == { b: '2' }

  Scenario: this won't be recognized as a test!
    * print 'Hi'
```

Note: the `karate.filterKeys()` line tosses a "expected match operator" error, which may be playing into this...

**Comment by jansorg** [comment] 2022-07-20 09:00
You're right, this is caused by the parsing error in line `* match karate.filterKeys(test, 'b') == { b: '2' }`.
This is now fixed for the next update.

**Closed** 2022-07-20 09:45 UTC
