### ISSUE TITLE
Examples table column headers are flagged as unused if the reference variable is included in a JSON blob

### ISSUE THREAD

**Issue by staffier** [karatelabs/karate-intellij-plugin#4] opened 2022-07-14 18:51 UTC
This will create a greyed-out, "unused" table column: 

```gherkin
* def testVar = { "test": "<value>" }

Examples: 
| value |
| 1     |
| 2     |
```

**Comment by ptrthomas** [comment] 2022-07-15 04:06
treating as duplicate of #1 we are planning some enhancements to handling of `Examples`

**Closed by ptrthomas** 2022-07-15 04:06 UTC
